apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "web.servers.org/v1alpha1",
          "kind": "WebServer",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "jws-operator"
            },
            "name": "webserver-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-07-31T08:28:44Z"
    operators.operatorframework.io/builder: operator-sdk-v1.41.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: jws-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: WebServer
      name: webservers.web.servers.org
      specDescriptors:
      - description: The base for the names of the deployed application resources
        displayName: Application Name
        path: applicationName
      - description: Desired number of replicas for the application
        displayName: Replicas
        path: replicas
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podCount
      - description: Use session clustering
        displayName: Enable Session Clustering in Tomcat
        path: useSessionClustering
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: Use Insights client (works only with JWS 6.1+ images)
        displayName: Enable Red Hat Insights
        path: useInsightsClient
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: (Deployment method 1) Application image
        displayName: Web Image
        path: webImage
      - description: (Deployment method 2) Image stream
        displayName: Web Image Stream
        path: webImageStream
      - description: TLS configuration for the WebServer
        displayName: TLS Configuration
        path: tlsConfig
      - description: Environment variables for the WebServer
        displayName: Environment Variables
        path: environmentVariables
      - description: Persistent logs configuration
        displayName: Persistent Logs
        path: persistentLogs
      - description: Configuration of the resources used by the WebServer e.g. CPU
          and memory.
        displayName: Pod Resources
        path: podResources
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:resourceRequirements
      - description: SecurityContext defines the security capabilities required to
          run the application.
        displayName: Security Context
        path: securityContext
      version: v1alpha1
  description: WebServer operator can manage JBoss Web Server images and Apache Tomcat
    images.
  displayName: WebServer
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - persistentvolumeclaims
          - pods
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - services/finalizers
          verbs:
          - update
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments/finalizers
          - jws-operator
          verbs:
          - update
        - apiGroups:
          - apps.openshift.io
          resources:
          - deploymentconfigs
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - build.openshift.io
          resources:
          - buildconfigs
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - build.openshift.io
          resources:
          - builds
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - image.openshift.io
          resources:
          - imagestreams
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          verbs:
          - create
          - get
          - grant
          - list
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes/custom-host
          verbs:
          - create
          - get
        - apiGroups:
          - web.servers.org
          resources:
          - webservers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - web.servers.org
          resources:
          - webservers/finalizers
          verbs:
          - update
        - apiGroups:
          - web.servers.org
          resources:
          - webservers/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: jws-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: jws-operator
          control-plane: controller-manager
        name: jws-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: jws-operator
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                app.kubernetes.io/name: jws-operator
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                image: quay.io/mmadzin/jws-operator:new-sdk
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: jws-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: jws-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - WebServer
  - JBoss
  - ApacheTomcat
  links:
  - name: Jws Operator
    url: https://jws-operator.domain
  maturity: alpha
  provider:
    name: WebServer community
  version: 0.0.1
