apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jws-operator
  name: jws-operator-webserver-viewer-role
rules:
- apiGroups:
  - web.servers.org
  resources:
  - webservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - web.servers.org
  resources:
  - webservers/status
  verbs:
  - get
