# This rule is not used by the project jws-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to web.servers.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jws-operator
    app.kubernetes.io/managed-by: kustomize
  name: webserver-viewer-role
rules:
- apiGroups:
  - web.servers.org
  resources:
  - webservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - web.servers.org
  resources:
  - webservers/status
  verbs:
  - get
