# permissions for end users to edit webservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jws-operator
    app.kubernetes.io/managed-by: kustomize
  name: webserver-editor-role
rules:
- apiGroups:
  - web.servers.org
  resources:
  - webservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - web.servers.org
  resources:
  - webservers/status
  verbs:
  - get
